/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateTaskRequest } from '../../models/create-task-request';
import { TaskDto } from '../../models/task-dto';

export interface CreateTask$Params {
      body: CreateTaskRequest
}

export function createTask(http: HttpClient, rootUrl: string, params: CreateTask$Params, context?: HttpContext): Observable<StrictHttpResponse<TaskDto>> {
  const rb = new RequestBuilder(rootUrl, createTask.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TaskDto>;
    })
  );
}

createTask.PATH = '/api/tasks';
