/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GtdStatus } from '../../models/gtd-status';
import { TaskDto } from '../../models/task-dto';

export interface GetTasks$Params {
  status?: GtdStatus;
  projectId?: string;
}

export function getTasks(http: HttpClient, rootUrl: string, params?: GetTasks$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TaskDto>>> {
  const rb = new RequestBuilder(rootUrl, getTasks.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('projectId', params.projectId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TaskDto>>;
    })
  );
}

getTasks.PATH = '/api/tasks';
