/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTaskRequest {
  category: (string | null);
  dueDate: (string | null);
  estimatedMinutes: number;
  notes: (string | null);
  projectId: (string | null);
  title: string;
}
