/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GtdStatus } from '../models/gtd-status';
export interface TaskDto {
  category: (string | null);
  completedAt: (string | null);
  createdAt: string;
  dueDate: (string | null);
  estimatedMinutes: number;
  id: string;
  notes: (string | null);
  projectId: (string | null);
  status: GtdStatus;
  title: string;
}
