/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GtdStatus } from '../models/gtd-status';
export interface UpdateTaskRequest {
  category: (string | null);
  dueDate: (string | null);
  estimatedMinutes: number;
  notes: (string | null);
  projectId: (string | null);
  status: GtdStatus;
  title: string;
}
