/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectStatus } from '../models/project-status';
export interface UpdateProjectRequest {
  name: string;
  outcome: (string | null);
  status: ProjectStatus;
}
